export const C = {
  accent:    '#5B68F5',
  accentL:   '#ECEEFF',
  accentLL:  '#F5F6FF',
  text:      '#1A1A2E',
  textMid:   '#8A8A9A',
  textLt:    '#C8C8D4',
  bg:        '#F7F6F3',
  white:     '#FFFFFF',
  track:     '#E5E5EA',
  ok:        '#16A34A',
  okL:       '#DCFCE7',
  warn:      '#D97706',
  warnL:     '#FEF3C7',
  err:       '#DC2626',
  errL:      '#FEE2E2',
  orange:    '#FF6B35',
  navy:      '#BCC0FF',
  bar:       '#AAB4FF',
} as const;
